kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: triplom  # Name of the cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.32.2  # Specific version of the node image
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
    kubeadmConfigPatches:
      - |
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: ClusterConfiguration
        metadata:
          name: config
        apiServer:
          extraArgs:
            enable-admission-plugins: NodeRestriction,PodSecurityPolicy  # Enable admission plugins for security
  - role: worker
    image: kindest/node:v1.32.2  # Ensure the same node image version is used
  - role: worker
    image: kindest/node:v1.32.2
networking:
  apiServerAddress: "127.0.0.1"  # API server address for security
  apiServerPort: 6443  # API server port
  podSubnet: "10.244.0.0/16"  # Define IP range for pods
  serviceSubnet: "10.96.0.0/12"  # Define subnet for services
featureGates:
  IPv6DualStack: true  # Enable dual-stack support (IPv4 and IPv6)
