apiVersion: v1
kind: Pod
metadata:
  name: triplom
  labels:
    run: triplom
    name: triplom
spec:
  containers:
  - image: nginx
    name: webserver
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /triplom
      name: primeiro-emptydir
    resources:
      limits:
        cpu: 1 
        memory: 128Mi
      requests:
        cpu: 0.5
        memory: 64Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 512Mi

