apiVersion: v1
kind: Pod
metadata:
  labels:
    run: triplom
    service: webserver
  name: triplom
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
  - image: busybox
    name: busybox
    args: 
    - sleep:
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
