apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app2
  template:
    metadata:
      labels:
        app: nginx-app2
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.1
        ports:
        - containerPort: 80 # Expose port 80 for HTTP traffic
        resources:
          limits:
            cpu: "500m" # Use "m" suffix for milliCPU
            memory: "256Mi"
          requests:
            cpu: "300m" # Use "m" suffix for milliCPU
            memory: "128Mi"
        livenessProbe: # Add a liveness probe to ensure container health
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe: # Add a readiness probe to ensure the container is ready to serve traffic
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts: # Define volume mounts if needed
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes: # Define volumes if needed
      - name: nginx-config
        configMap:
          name: nginx-config # Assuming a ConfigMap named "nginx-config" exists

