apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deployment2
  name: nginx-deployment2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-deployment2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment2
    spec:
      containers:
      - image: mginx
        name: mginx
        resources: {}
status: {}
